board/urls.py
# board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # articles/create/
    path('create/', views.create_article, name='create_article'),
    # articles/
    path('', views.article_index, name='article_index'),
    # articles/1/
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    # article/1/update/
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    # article/1/delete/
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    # articles/1/comments/create/
    path('<int:article_pk>/comments/create/', views.create_comment, name='create_comment'),
    # articles/1/comments/2/delete/
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    # articles/1/like/
    path('<int:article_pk>/like/', views.like_article, name='like_article'),
]

one_to_many/urls.py
# Master urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

board/models.py
# board/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='articles'
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_articles'
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    content = models.CharField(max_length=200)
    # foreign key 쓰면 필드명에 _id 붙이지 않기.
    # migrate 하면 알아서 뒤에 _id 붙음.
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

board/forms.py
# board/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)
        # exclude = ('user', )


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        min_length=2, max_length=200,
        widget=forms.TextInput(attrs={'autofocus': True})
    )
    class Meta:
        model = Comment
        # fields = ('content', )
        exclude = ('article', 'user',)

board/views.py
# board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import (require_http_methods,
                                          require_POST,
                                          require_safe, )

from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


@login_required
@require_http_methods(['GET', 'POST'])
def create_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)        
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('board:article_detail', article.pk)
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'board/form.html', context)


@require_safe  # GET, (HEAD) 요청만 허용하겠다.
def article_index(request):
    from django.db.models import Count  # 원래는 최상단
    '''
    Article 테이블에 가상의 컬럼을 만들며(annotate),
    컬럼 이름은 like_count고,
    like_users를 Count해서 채울 것이며,
    이 가상의 컬럼을 기준으로 내림차순 정렬하겠다.
    '''
    articles = Article.objects.annotate(like_count=Count('like_users')).order_by('-like_count')
    # articles = Article.objects.all()
    context = {'articles': articles, }
    return render(request, 'board/index.html', context)


@require_safe  # GET, (HEAD) 요청만 허용하겠다.
def article_detail(request, article_pk):
    # article 상세 페이지
    article = get_object_or_404(Article, pk=article_pk)
    # 댓글 입력 창 => _comment_form.html
    form = CommentForm()
    # 좋아요 버튼 UI 결정 Flag
    is_like = article.like_users.filter(pk=request.user.pk).exists()

    context = {
        'article': article,
        'form': form,
        'is_like': is_like,
    }
    return render(request, 'board/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 작성자 아니면 돌려보내기
    if request.user != article.user:
        return redirect('board:article_detail', article.pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)        
        if form.is_valid():
            # 기존에 저장된 user_id 갱신할 필요가 없기때문에 commit=False 필요 X
            article = form.save()
            return redirect('board:article_detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {'form': form}
    return render(request, 'board/form.html', context)


@login_required
@require_POST
def delete_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        article.delete()
        return redirect('board:article_index')
    else:
        return redirect('board:article_detail', article.pk)


@login_required
@require_POST
def create_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm(request.POST)
    
    if form.is_valid():
        # 완전 저장하려고 하면 NOT NULL 에러 뜨니까, 직전에 멈춰 주세요.
        comment = form.save(commit=False)
        # 나머지는 직접 할게요
        comment.user = request.user
        comment.article = article
        comment.save()

    return redirect('board:article_detail', article.pk)


@login_required
@require_POST
def delete_comment(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('board:article_detail', article.pk)


@login_required
@require_POST
def like_article(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    
    # article 에 좋아요 한 사람들 중에, user가 있나요?
    # is_like = user in article.like_users.all() => 효율 안좋음..
    is_like = article.like_users.filter(pk=user.pk).exists()

    # 기존에 좋아요를 했으면
    if is_like:
        # 좋아요 테이블에서 삭제
        user.like_articles.remove(article)
    # 아니라면
    else:
        # 좋아요 테이블에 추가
        user.like_articles.add(article)
    return redirect('board:article_detail', article.pk)

board/templates/board/_comment_form.html
<!-- board/_comment_form.html -->

{% comment %} 댓글 입력창 {% endcomment %}
<form action="{% url 'board:create_comment' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button>얍!</button>
</form>

board/templates/board/_comment_list.html
<!-- board/_comment_list.html -->

{% comment %} 댓글 목록 조회 (댓글 삭제) {% endcomment %}
<ul>
    {% for comment in article.comments.all %}
    <li>
        {{ comment.user }} - {{ comment.content }}
        {% if request.user == comment.user %}
        <form action="{% url 'board:delete_comment' article.pk comment.pk %}" method="POST" style="display: inline-block;">
            {% csrf_token %}
            <button>x</button>
        </form>
        {% endif %}
    </li>
    {% endfor %}
</ul>

board/templates/board/detail.html
<!-- board/detail.html -->
{% extends 'base.html' %}

{% block content %}
<h1>{{ article.title }} ({{ article.comments.count }})</h1>
<p>by - {{ article.user.username }}</p>

<p>{{ article.content }}</p>

{% comment %} 좋아요 UI {% endcomment %}
{% if request.user.is_authenticated %}
<form action="{% url 'board:like_article' article.pk %}" method="POST">
  {% csrf_token %}
  
  {% if is_like %}
  <button>좋아요 취소</button>
  {% else %}
  <button>좋아요</button>
  {% endif %}

  <span>+{{ article.like_users.count }}</span>
</form>
{% endif %}

{% comment %} 수정/삭제 UI {% endcomment %}
{% if request.user == article.user %}
<div>
  <a href="{% url 'board:update_article' article.pk %}">
    <button class="btn btn-warning">Update</button>
  </a>
</div>
  
<div>
  <form action="{% url 'board:delete_article' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">Delete</button>
  </form>
</div>
{% endif %}
<hr>
<!-- component(부품) -->
{% if request.user.is_authenticated %}
{% include 'board/_comment_form.html' %}
{% endif %}

{% include 'board/_comment_list.html' %}
{% endblock content %}

board/templates/board/form.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <button>GO</button>
    </p>
</form>

{% endblock content %}

board/templates/board/index.html
{% extends 'base.html' %}

{% block content %}

<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'board:article_detail' article.pk %}">
            {{ article.title }}
        </a>({{ article.comments.count }}) | +{{ article.like_users.count }}
    </li>
    {% endfor %}
</ul>

{% endblock content %}