accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # accounts/signup/
    path('signup/', views.signup, name='signup'),
    # accounts/login/
    path('login/', views.login, name='login'),
    # accounts/logout/
    path('logout/', views.logout, name='logout'),

    #(아래는 다루지 않음)
    # accounts/profile/neo/
    path('profile/<str:username>/', views.profile, name='profile'),
    # 회원정보 변경/삭제 
    # accounts/update/
    path('update/', views.update, name='update'),
    # accounts/delete/
    path('delete/', views.delete, name='delete'),
    # accounts/password/
    path('password/', views.password, name='password'),
]

board/urls.py
# board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # articles/create/
    path('create/', views.create_article, name='create_article'),
    # articles/
    path('', views.article_index, name='article_index'),
    # articles/1/
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    # article/1/update/
    path('<int:article_pk>/update/', views.update_article, name='update_article'),
    # article/1/delete/
    path('<int:article_pk>/delete/', views.delete_article, name='delete_article'),
    # articles/1/comments/create/
    path('<int:article_pk>/comments/create/', views.create_comment, name='create_comment'),
    # articles/1/comments/2/delete/
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.delete_comment, name='delete_comment'),
    # articles/1/like/
    path('<int:article_pk>/like/', views.like_article, name='like_article'),
]

one_to_many/urls.py
# Master urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'board:article_index' %}">Home</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'board:create_article' %}">New Article</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        <li><a href="{% url 'accounts:profile' user.username %}">{{ user.username }}'s profile</a></li>
        {% else %}
        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}
    </ul>
    <hr>
    {% block content %}{% endblock content %}
</body>
</html>